# Website details
name: Veri Veri Anadolu
description: illere göre bilgiler
email: otomatikmuhendis@yahoo.com
author: olcay
lang: tr
locale: tr_TR

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: Europe/Istanbul
paginateLabel: page
paginate_path: "page/:num"
permalink: /veri/:title
baseurl: http://anadolu.otomatikmuhendis.com
github: https://github.com/otomatikmuhendis/anadolu

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
